# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: World.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='World.proto',
  package='World',
  serialized_pb='\n\x0bWorld.proto\x12\x05World\"\xac\x01\n\x05World\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05width\x18\x02 \x02(\x05\x12\x0e\n\x06height\x18\x03 \x02(\x05\x12)\n\theightMap\x18\x04 \x02(\x0b\x32\x16.World.World.HeightMap\x1a\x19\n\x08\x46loatRow\x12\r\n\x05\x63\x65lls\x18\x01 \x03(\x02\x1a\x30\n\tHeightMap\x12#\n\x04rows\x18\x01 \x03(\x0b\x32\x15.World.World.FloatRow')




_WORLD_FLOATROW = _descriptor.Descriptor(
  name='FloatRow',
  full_name='World.World.FloatRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cells', full_name='World.World.FloatRow.cells', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=120,
  serialized_end=145,
)

_WORLD_HEIGHTMAP = _descriptor.Descriptor(
  name='HeightMap',
  full_name='World.World.HeightMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='World.World.HeightMap.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=147,
  serialized_end=195,
)

_WORLD = _descriptor.Descriptor(
  name='World',
  full_name='World.World',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='World.World.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='World.World.width', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='World.World.height', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heightMap', full_name='World.World.heightMap', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_WORLD_FLOATROW, _WORLD_HEIGHTMAP, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=195,
)

_WORLD_FLOATROW.containing_type = _WORLD;
_WORLD_HEIGHTMAP.fields_by_name['rows'].message_type = _WORLD_FLOATROW
_WORLD_HEIGHTMAP.containing_type = _WORLD;
_WORLD.fields_by_name['heightMap'].message_type = _WORLD_HEIGHTMAP
DESCRIPTOR.message_types_by_name['World'] = _WORLD

class World(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class FloatRow(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _WORLD_FLOATROW

    # @@protoc_insertion_point(class_scope:World.World.FloatRow)

  class HeightMap(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _WORLD_HEIGHTMAP

    # @@protoc_insertion_point(class_scope:World.World.HeightMap)
  DESCRIPTOR = _WORLD

  # @@protoc_insertion_point(class_scope:World.World)


# @@protoc_insertion_point(module_scope)
