(define (script-fu-biomes-and-vegetation img
                                         base)
	(gimp-context-set-sample-threshold-int 0)
	(gimp-palette-set-foreground "#000000")
	(let* ( 
		(polar-ice-layer base)
		(subpolar-dry-tundra-layer base)
		(subpolar-moist-tundra-layer base)
		(subpolar-wet-tundra-layer base)
		(subpolar-rain-tundra-layer base)
		(polar-desert-layer base)
		(boreal-desert-layer base)
		(cool-temperate-desert-layer base)
		(warm-temperate-desert-layer base)
		(subtropical-desert-layer base)
		(tropical-desert-layer base)
		(boreal-rain-forest-layer base)
		(cool-temperate-rain-forest-layer base)
		(warm-temperate-rain-forest-layer base)
		(subtropical-rain-forest-layer base)
		(tropical-rain-forest-layer base)
		(boreal-wet-forest-layer base)
		(cool-temperate-wet-forest-layer base)
		(warm-temperate-wet-forest-layer base)
		(subtropical-wet-forest-layer base)
		(tropical-wet-forest-layer base)
		(boreal-moist-forest-layer base)
		(cool-temperate-moist-forest-layer base)
		(warm-temperate-moist-forest-layer base)
		(subtropical-moist-forest-layer base)
		(tropical-moist-forest-layer base)
		(warm-temperate-dry-forest-layer base)
		(subtropical-dry-forest-layer base)
		(tropical-dry-forest-layer base)
		(boreal-dry-scrub-layer base)
		(cool-temperate-desert-scrub-layer base)
		(warm-temperate-desert-scrub-layer base)
		(subtropical-desert-scrub-layer base)
		(tropical-desert-scrub-layer base)
		(cool-temperate-steppe-layer base)
		(warm-temperate-thorn-scrub-layer base)
		(subtropical-thorn-woodland-layer base)
		(tropical-thorn-woodland-layer base)
		(tropical-very-dry-forest-layer base)
		(tundra-group base)
		(forest-tundra-group base)
		(cold-parklands-group base)
		(boreal-forest-group base)
		(temperate-forest-group base)
		(steppe-group base)
		(cool-desert-group base)
		(warm-temperate-forest-group base)
		(chapparal-group base)
		(hot-desert-group base)
		(tropical-semiarid-group base)
		(tropical-dry-forest-group base)
		(tropical-seasonal-forest-group base)
		(tropical-rain-forest-group base)
		(ice-layer base)
		(tundra-layer base)
		(cold-parklands-layer base)
		(coniferous-forest-layer base)
		(mixed-forest-layer base)
		(steppe-layer base)
		(cool-desert-layer base)
		(deciduous-forest-layer base)
		(chapparal-layer base)
		(hot-desert-layer base)
		(savanna-layer base)
		(tropical-dry-forest-layer2 base)
		(tropical-seasonal-forest-layer2 base)
		(tropical-rain-forest-layer2 base)		)
	(set! polar-ice-layer (car (gimp-layer-new img 4096 2048 1 "polar ice" 100 0)))
	(gimp-image-add-layer img polar-ice-layer 0)
	(gimp-image-select-color img 2 base "#FFFFFF")
	(gimp-edit-fill polar-ice-layer 0)
	(set! subpolar-dry-tundra-layer (car (gimp-layer-new img 4096 2048 1 "subpolar dry tundra" 100 0)))
	(gimp-image-add-layer img subpolar-dry-tundra-layer 0)
	(gimp-image-select-color img 2 base "#808080")
	(gimp-edit-fill subpolar-dry-tundra-layer 0)
	(set! subpolar-moist-tundra-layer (car (gimp-layer-new img 4096 2048 1 "subpolar moist tundra" 100 0)))
	(gimp-image-add-layer img subpolar-moist-tundra-layer 0)
	(gimp-image-select-color img 2 base "#608080")
	(gimp-edit-fill subpolar-moist-tundra-layer 0)
	(set! subpolar-wet-tundra-layer (car (gimp-layer-new img 4096 2048 1 "subpolar wet tundra" 100 0)))
	(gimp-image-add-layer img subpolar-wet-tundra-layer 0)
	(gimp-image-select-color img 2 base "#408080")
	(gimp-edit-fill subpolar-wet-tundra-layer 0)
	(set! subpolar-rain-tundra-layer (car (gimp-layer-new img 4096 2048 1 "subpolar rain tundra" 100 0)))
	(gimp-image-add-layer img subpolar-rain-tundra-layer 0)
	(gimp-image-select-color img 2 base "#2080C0")
	(gimp-edit-fill subpolar-rain-tundra-layer 0)
	(set! polar-desert-layer (car (gimp-layer-new img 4096 2048 1 "polar desert" 100 0)))
	(gimp-image-add-layer img polar-desert-layer 0)
	(gimp-image-select-color img 2 base "#C0C0C0")
	(gimp-edit-fill polar-desert-layer 0)
	(set! boreal-desert-layer (car (gimp-layer-new img 4096 2048 1 "boreal desert" 100 0)))
	(gimp-image-add-layer img boreal-desert-layer 0)
	(gimp-image-select-color img 2 base "#A0A080")
	(gimp-edit-fill boreal-desert-layer 0)
	(set! cool-temperate-desert-layer (car (gimp-layer-new img 4096 2048 1 "cool temperate desert" 100 0)))
	(gimp-image-add-layer img cool-temperate-desert-layer 0)
	(gimp-image-select-color img 2 base "#C0C080")
	(gimp-edit-fill cool-temperate-desert-layer 0)
	(set! warm-temperate-desert-layer (car (gimp-layer-new img 4096 2048 1 "warm temperate desert" 100 0)))
	(gimp-image-add-layer img warm-temperate-desert-layer 0)
	(gimp-image-select-color img 2 base "#E0E080")
	(gimp-edit-fill warm-temperate-desert-layer 0)
	(set! subtropical-desert-layer (car (gimp-layer-new img 4096 2048 1 "subtropical desert" 100 0)))
	(gimp-image-add-layer img subtropical-desert-layer 0)
	(gimp-image-select-color img 2 base "#F0F080")
	(gimp-edit-fill subtropical-desert-layer 0)
	(set! tropical-desert-layer (car (gimp-layer-new img 4096 2048 1 "tropical desert" 100 0)))
	(gimp-image-add-layer img tropical-desert-layer 0)
	(gimp-image-select-color img 2 base "#FFFF80")
	(gimp-edit-fill tropical-desert-layer 0)
	(set! boreal-rain-forest-layer (car (gimp-layer-new img 4096 2048 1 "boreal rain forest" 100 0)))
	(gimp-image-add-layer img boreal-rain-forest-layer 0)
	(gimp-image-select-color img 2 base "#20A0C0")
	(gimp-edit-fill boreal-rain-forest-layer 0)
	(set! cool-temperate-rain-forest-layer (car (gimp-layer-new img 4096 2048 1 "cool temperate rain forest" 100 0)))
	(gimp-image-add-layer img cool-temperate-rain-forest-layer 0)
	(gimp-image-select-color img 2 base "#20C0C0")
	(gimp-edit-fill cool-temperate-rain-forest-layer 0)
	(set! warm-temperate-rain-forest-layer (car (gimp-layer-new img 4096 2048 1 "warm temperate rain forest" 100 0)))
	(gimp-image-add-layer img warm-temperate-rain-forest-layer 0)
	(gimp-image-select-color img 2 base "#20E0C0")
	(gimp-edit-fill warm-temperate-rain-forest-layer 0)
	(set! subtropical-rain-forest-layer (car (gimp-layer-new img 4096 2048 1 "subtropical rain forest" 100 0)))
	(gimp-image-add-layer img subtropical-rain-forest-layer 0)
	(gimp-image-select-color img 2 base "#20F0B0")
	(gimp-edit-fill subtropical-rain-forest-layer 0)
	(set! tropical-rain-forest-layer (car (gimp-layer-new img 4096 2048 1 "tropical rain forest" 100 0)))
	(gimp-image-add-layer img tropical-rain-forest-layer 0)
	(gimp-image-select-color img 2 base "#20FFA0")
	(gimp-edit-fill tropical-rain-forest-layer 0)
	(set! boreal-wet-forest-layer (car (gimp-layer-new img 4096 2048 1 "boreal wet forest" 100 0)))
	(gimp-image-add-layer img boreal-wet-forest-layer 0)
	(gimp-image-select-color img 2 base "#40A090")
	(gimp-edit-fill boreal-wet-forest-layer 0)
	(set! cool-temperate-wet-forest-layer (car (gimp-layer-new img 4096 2048 1 "cool temperate wet forest" 100 0)))
	(gimp-image-add-layer img cool-temperate-wet-forest-layer 0)
	(gimp-image-select-color img 2 base "#40C090")
	(gimp-edit-fill cool-temperate-wet-forest-layer 0)
	(set! warm-temperate-wet-forest-layer (car (gimp-layer-new img 4096 2048 1 "warm temperate wet forest" 100 0)))
	(gimp-image-add-layer img warm-temperate-wet-forest-layer 0)
	(gimp-image-select-color img 2 base "#40E090")
	(gimp-edit-fill warm-temperate-wet-forest-layer 0)
	(set! subtropical-wet-forest-layer (car (gimp-layer-new img 4096 2048 1 "subtropical wet forest" 100 0)))
	(gimp-image-add-layer img subtropical-wet-forest-layer 0)
	(gimp-image-select-color img 2 base "#40F090")
	(gimp-edit-fill subtropical-wet-forest-layer 0)
	(set! tropical-wet-forest-layer (car (gimp-layer-new img 4096 2048 1 "tropical wet forest" 100 0)))
	(gimp-image-add-layer img tropical-wet-forest-layer 0)
	(gimp-image-select-color img 2 base "#40FF90")
	(gimp-edit-fill tropical-wet-forest-layer 0)
	(set! boreal-moist-forest-layer (car (gimp-layer-new img 4096 2048 1 "boreal moist forest" 100 0)))
	(gimp-image-add-layer img boreal-moist-forest-layer 0)
	(gimp-image-select-color img 2 base "#60A080")
	(gimp-edit-fill boreal-moist-forest-layer 0)
	(set! cool-temperate-moist-forest-layer (car (gimp-layer-new img 4096 2048 1 "cool temperate moist forest" 100 0)))
	(gimp-image-add-layer img cool-temperate-moist-forest-layer 0)
	(gimp-image-select-color img 2 base "#60C080")
	(gimp-edit-fill cool-temperate-moist-forest-layer 0)
	(set! warm-temperate-moist-forest-layer (car (gimp-layer-new img 4096 2048 1 "warm temperate moist forest" 100 0)))
	(gimp-image-add-layer img warm-temperate-moist-forest-layer 0)
	(gimp-image-select-color img 2 base "#60E080")
	(gimp-edit-fill warm-temperate-moist-forest-layer 0)
	(set! subtropical-moist-forest-layer (car (gimp-layer-new img 4096 2048 1 "subtropical moist forest" 100 0)))
	(gimp-image-add-layer img subtropical-moist-forest-layer 0)
	(gimp-image-select-color img 2 base "#60F080")
	(gimp-edit-fill subtropical-moist-forest-layer 0)
	(set! tropical-moist-forest-layer (car (gimp-layer-new img 4096 2048 1 "tropical moist forest" 100 0)))
	(gimp-image-add-layer img tropical-moist-forest-layer 0)
	(gimp-image-select-color img 2 base "#60FF80")
	(gimp-edit-fill tropical-moist-forest-layer 0)
	(set! warm-temperate-dry-forest-layer (car (gimp-layer-new img 4096 2048 1 "warm temperate dry forest" 100 0)))
	(gimp-image-add-layer img warm-temperate-dry-forest-layer 0)
	(gimp-image-select-color img 2 base "#80E080")
	(gimp-edit-fill warm-temperate-dry-forest-layer 0)
	(set! subtropical-dry-forest-layer (car (gimp-layer-new img 4096 2048 1 "subtropical dry forest" 100 0)))
	(gimp-image-add-layer img subtropical-dry-forest-layer 0)
	(gimp-image-select-color img 2 base "#80F080")
	(gimp-edit-fill subtropical-dry-forest-layer 0)
	(set! tropical-dry-forest-layer (car (gimp-layer-new img 4096 2048 1 "tropical dry forest" 100 0)))
	(gimp-image-add-layer img tropical-dry-forest-layer 0)
	(gimp-image-select-color img 2 base "#80FF80")
	(gimp-edit-fill tropical-dry-forest-layer 0)
	(set! boreal-dry-scrub-layer (car (gimp-layer-new img 4096 2048 1 "boreal dry scrub" 100 0)))
	(gimp-image-add-layer img boreal-dry-scrub-layer 0)
	(gimp-image-select-color img 2 base "#80A080")
	(gimp-edit-fill boreal-dry-scrub-layer 0)
	(set! cool-temperate-desert-scrub-layer (car (gimp-layer-new img 4096 2048 1 "cool temperate desert scrub" 100 0)))
	(gimp-image-add-layer img cool-temperate-desert-scrub-layer 0)
	(gimp-image-select-color img 2 base "#A0C080")
	(gimp-edit-fill cool-temperate-desert-scrub-layer 0)
	(set! warm-temperate-desert-scrub-layer (car (gimp-layer-new img 4096 2048 1 "warm temperate desert scrub" 100 0)))
	(gimp-image-add-layer img warm-temperate-desert-scrub-layer 0)
	(gimp-image-select-color img 2 base "#C0E080")
	(gimp-edit-fill warm-temperate-desert-scrub-layer 0)
	(set! subtropical-desert-scrub-layer (car (gimp-layer-new img 4096 2048 1 "subtropical desert scrub" 100 0)))
	(gimp-image-add-layer img subtropical-desert-scrub-layer 0)
	(gimp-image-select-color img 2 base "#D0F080")
	(gimp-edit-fill subtropical-desert-scrub-layer 0)
	(set! tropical-desert-scrub-layer (car (gimp-layer-new img 4096 2048 1 "tropical desert scrub" 100 0)))
	(gimp-image-add-layer img tropical-desert-scrub-layer 0)
	(gimp-image-select-color img 2 base "#E0FF80")
	(gimp-edit-fill tropical-desert-scrub-layer 0)
	(set! cool-temperate-steppe-layer (car (gimp-layer-new img 4096 2048 1 "cool temperate steppe" 100 0)))
	(gimp-image-add-layer img cool-temperate-steppe-layer 0)
	(gimp-image-select-color img 2 base "#80C080")
	(gimp-edit-fill cool-temperate-steppe-layer 0)
	(set! warm-temperate-thorn-scrub-layer (car (gimp-layer-new img 4096 2048 1 "warm temperate thorn scrub" 100 0)))
	(gimp-image-add-layer img warm-temperate-thorn-scrub-layer 0)
	(gimp-image-select-color img 2 base "#A0E080")
	(gimp-edit-fill warm-temperate-thorn-scrub-layer 0)
	(set! subtropical-thorn-woodland-layer (car (gimp-layer-new img 4096 2048 1 "subtropical thorn woodland" 100 0)))
	(gimp-image-add-layer img subtropical-thorn-woodland-layer 0)
	(gimp-image-select-color img 2 base "#B0F080")
	(gimp-edit-fill subtropical-thorn-woodland-layer 0)
	(set! tropical-thorn-woodland-layer (car (gimp-layer-new img 4096 2048 1 "tropical thorn woodland" 100 0)))
	(gimp-image-add-layer img tropical-thorn-woodland-layer 0)
	(gimp-image-select-color img 2 base "#C0FF80")
	(gimp-edit-fill tropical-thorn-woodland-layer 0)
	(set! tropical-very-dry-forest-layer (car (gimp-layer-new img 4096 2048 1 "tropical very dry forest" 100 0)))
	(gimp-image-add-layer img tropical-very-dry-forest-layer 0)
	(gimp-image-select-color img 2 base "#A0FF80")
	(gimp-edit-fill tropical-very-dry-forest-layer 0)
	(set! tropical-rain-forest-group (car (gimp-layer-group-new img)))
	(gimp-image-insert-layer img tropical-rain-forest-group 0 0)
	(gimp-item-set-name tropical-rain-forest-group "Tropical Rain Forest Group")
	(gimp-image-reorder-item img tropical-rain-forest-layer tropical-rain-forest-group 0)
	(gimp-image-reorder-item img tropical-wet-forest-layer tropical-rain-forest-group 0)
	(gimp-image-reorder-item img tropical-moist-forest-layer tropical-rain-forest-group 0)
	(gimp-image-reorder-item img subtropical-rain-forest-layer tropical-rain-forest-group 0)
	(gimp-image-reorder-item img subtropical-wet-forest-layer tropical-rain-forest-group 0)
	(set! tropical-seasonal-forest-group (car (gimp-layer-group-new img)))
	(gimp-image-insert-layer img tropical-seasonal-forest-group 0 0)
	(gimp-item-set-name tropical-seasonal-forest-group "Tropical Seasonal Forest Group")
	(gimp-image-reorder-item img subtropical-moist-forest-layer tropical-seasonal-forest-group 0)
	(set! tropical-dry-forest-group (car (gimp-layer-group-new img)))
	(gimp-image-insert-layer img tropical-dry-forest-group 0 0)
	(gimp-item-set-name tropical-dry-forest-group "Tropical Dry Forest Group")
	(gimp-image-reorder-item img tropical-dry-forest-layer tropical-dry-forest-group 0)
	(gimp-image-reorder-item img subtropical-dry-forest-layer tropical-dry-forest-group 0)
	(set! tropical-semiarid-group (car (gimp-layer-group-new img)))
	(gimp-image-insert-layer img tropical-semiarid-group 0 0)
	(gimp-item-set-name tropical-semiarid-group "Tropical Semi-Arid Group")
	(gimp-image-reorder-item img tropical-very-dry-forest-layer tropical-semiarid-group 0)
	(gimp-image-reorder-item img tropical-thorn-woodland-layer tropical-semiarid-group 0)
	(gimp-image-reorder-item img subtropical-thorn-woodland-layer tropical-semiarid-group 0)
	(set! hot-desert-group (car (gimp-layer-group-new img)))
	(gimp-image-insert-layer img hot-desert-group 0 0)
	(gimp-item-set-name hot-desert-group "Hot Desert Group")
	(gimp-image-reorder-item img tropical-desert-scrub-layer hot-desert-group 0)
	(gimp-image-reorder-item img tropical-desert-layer hot-desert-group 0)
	(gimp-image-reorder-item img subtropical-desert-scrub-layer hot-desert-group 0)
	(gimp-image-reorder-item img subtropical-desert-layer hot-desert-group 0)
	(gimp-image-reorder-item img warm-temperate-desert-scrub-layer hot-desert-group 0)
	(gimp-image-reorder-item img warm-temperate-desert-layer hot-desert-group 0)
	(set! chapparal-group (car (gimp-layer-group-new img)))
	(gimp-image-insert-layer img chapparal-group 0 0)
	(gimp-item-set-name chapparal-group "Chapparal Group")
	(gimp-image-reorder-item img warm-temperate-dry-forest-layer chapparal-group 0)
	(gimp-image-reorder-item img warm-temperate-thorn-scrub-layer chapparal-group 0)
	(set! warm-temperate-forest-group (car (gimp-layer-group-new img)))
	(gimp-image-insert-layer img warm-temperate-forest-group 0 0)
	(gimp-item-set-name warm-temperate-forest-group "Warm Temperate Forest Group")
	(gimp-image-reorder-item img warm-temperate-rain-forest-layer warm-temperate-forest-group 0)
	(gimp-image-reorder-item img warm-temperate-wet-forest-layer warm-temperate-forest-group 0)
	(gimp-image-reorder-item img warm-temperate-moist-forest-layer warm-temperate-forest-group 0)
	(set! cool-desert-group (car (gimp-layer-group-new img)))
	(gimp-image-insert-layer img cool-desert-group 0 0)
	(gimp-item-set-name cool-desert-group "Cool Desert Group")
	(gimp-image-reorder-item img cool-temperate-desert-scrub-layer cool-desert-group 0)
	(gimp-image-reorder-item img cool-temperate-desert-layer cool-desert-group 0)
	(set! steppe-group (car (gimp-layer-group-new img)))
	(gimp-image-insert-layer img steppe-group 0 0)
	(gimp-item-set-name steppe-group "Steppes Group")
	(gimp-image-reorder-item img cool-temperate-steppe-layer steppe-group 0)
	(set! temperate-forest-group (car (gimp-layer-group-new img)))
	(gimp-image-insert-layer img temperate-forest-group 0 0)
	(gimp-item-set-name temperate-forest-group "Temperate Forest Group")
	(gimp-image-reorder-item img cool-temperate-rain-forest-layer temperate-forest-group 0)
	(gimp-image-reorder-item img cool-temperate-wet-forest-layer temperate-forest-group 0)
	(gimp-image-reorder-item img cool-temperate-moist-forest-layer temperate-forest-group 0)
	(set! boreal-forest-group (car (gimp-layer-group-new img)))
	(gimp-image-insert-layer img boreal-forest-group 0 0)
	(gimp-item-set-name boreal-forest-group "Boreal Forest Group")
	(gimp-image-reorder-item img boreal-rain-forest-layer boreal-forest-group 0)
	(gimp-image-reorder-item img boreal-wet-forest-layer boreal-forest-group 0)
	(gimp-image-reorder-item img boreal-moist-forest-layer boreal-forest-group 0)
	(set! cold-parklands-group (car (gimp-layer-group-new img)))
	(gimp-image-insert-layer img cold-parklands-group 0 0)
	(gimp-item-set-name cold-parklands-group "Cold Parklands Group")
	(gimp-image-reorder-item img boreal-dry-scrub-layer cold-parklands-group 0)
	(gimp-image-reorder-item img boreal-desert-layer cold-parklands-group 0)
	(gimp-image-reorder-item img subpolar-dry-tundra-layer cold-parklands-group 0)
	(set! forest-tundra-group (car (gimp-layer-group-new img)))
	(gimp-image-insert-layer img forest-tundra-group 0 0)
	(gimp-item-set-name forest-tundra-group "Tundra Group")
	(gimp-image-reorder-item img subpolar-rain-tundra-layer forest-tundra-group 0)
	(gimp-image-reorder-item img subpolar-wet-tundra-layer forest-tundra-group 0)
	(gimp-image-reorder-item img subpolar-moist-tundra-layer forest-tundra-group 0)
	(set! tundra-group (car (gimp-layer-group-new img)))
	(gimp-image-insert-layer img tundra-group 0 0)
	(gimp-item-set-name tundra-group "Ice Group")
	(gimp-image-reorder-item img polar-desert-layer tundra-group 0)
	(gimp-image-reorder-item img polar-ice-layer tundra-group 0)
	
	(set! tropical-rain-forest-layer2 (car (gimp-layer-new img 4096 2048 1 "Tropical Rain Forest" 100 0)))
	(gimp-image-add-layer img tropical-rain-forest-layer2 0)
	(gimp-image-select-color img 2 base "#40F090")
	(gimp-image-select-color img 0 base "#20F0B0")
	(gimp-image-select-color img 0 base "#60FF80")
	(gimp-image-select-color img 0 base "#40FF90")
	(gimp-image-select-color img 0 base "#20FFA0")
	(gimp-palette-set-foreground "#1cb242")
	(gimp-edit-fill tropical-rain-forest-layer2 0)
	
	(set! tropical-seasonal-forest-layer2 (car (gimp-layer-new img 4096 2048 1 "Tropical Seasonal Forest" 100 0)))
	(gimp-image-add-layer img tropical-seasonal-forest-layer2 0)
	(gimp-image-select-color img 2 base "#60F080")
	(gimp-palette-set-foreground "#25e750")
	(gimp-edit-fill tropical-seasonal-forest-layer2 0)
	
	(set! tropical-dry-forest-layer2 (car (gimp-layer-new img 4096 2048 1 "Tropical Dry Forest" 100 0)))
	(gimp-image-add-layer img tropical-dry-forest-layer2 0)
	(gimp-image-select-color img 2 base "#80F080")
	(gimp-image-select-color img 0 base "#80FF80")
	(gimp-palette-set-foreground "#4dff4d")
	(gimp-edit-fill tropical-dry-forest-layer2 0)
	
	(set! savanna-layer (car (gimp-layer-new img 4096 2048 1 "Savanna" 100 0)))
	(gimp-image-add-layer img savanna-layer 0)
	(gimp-image-select-color img 2 base "#B0F080")
	(gimp-image-select-color img 0 base "#C0FF80")
	(gimp-image-select-color img 0 base "#A0FF80")
	(gimp-palette-set-foreground "#90ff4d")
	(gimp-edit-fill savanna-layer 0)
	
	(set! hot-desert-layer (car (gimp-layer-new img 4096 2048 1 "Hot Desert" 100 0)))
	(gimp-image-add-layer img hot-desert-layer 0)
	(gimp-image-select-color img 2 base "#E0E080")
	(gimp-image-select-color img 0 base "#C0E080")
	(gimp-image-select-color img 0 base "#F0F080")
	(gimp-image-select-color img 0 base "#D0F080")
	(gimp-image-select-color img 0 base "#FFFF80")
	(gimp-image-select-color img 0 base "#E0FF80")
	(gimp-palette-set-foreground "#d4ff4d")
	(gimp-edit-fill hot-desert-layer 0)
	
	(set! chapparal-layer (car (gimp-layer-new img 4096 2048 1 "Chapparal" 100 0)))
	(gimp-image-add-layer img chapparal-layer 0)
	(gimp-image-select-color img 2 base "#A0E080")
	(gimp-image-select-color img 0 base "#80E080")
	(gimp-palette-set-foreground "#52cd52")
	(gimp-edit-fill chapparal-layer 0)
	
	(set! deciduous-forest-layer (car (gimp-layer-new img 4096 2048 1 "Deciduous Forest" 100 0)))
	(gimp-image-add-layer img deciduous-forest-layer 0)
	(gimp-image-select-color img 2 base "#60E080")
	(gimp-image-select-color img 0 base "#40E090")
	(gimp-image-select-color img 0 base "#20E0C0")
	(gimp-palette-set-foreground "#00cd7b")
	(gimp-edit-fill deciduous-forest-layer 0)
	
	(set! cool-desert-layer (car (gimp-layer-new img 4096 2048 1 "Cool Desert" 100 0)))
	(gimp-image-add-layer img cool-desert-layer 0)
	(gimp-image-select-color img 2 base "#C0C080")
	(gimp-image-select-color img 0 base "#A0C080")
	(gimp-palette-set-foreground "#aac066")
	(gimp-edit-fill cool-desert-layer 0)
	
	(set! steppe-layer (car (gimp-layer-new img 4096 2048 1 "Steppes" 100 0)))
	(gimp-image-add-layer img steppe-layer 0)
	(gimp-image-select-color img 2 base "#80C080")
	(gimp-palette-set-foreground "#529a52")
	(gimp-edit-fill steppe-layer 0)
	
	(set! mixed-forest-layer (car (gimp-layer-new img 4096 2048 1 "Mixed Forest" 100 0)))
	(gimp-image-add-layer img mixed-forest-layer 0)
	(gimp-image-select-color img 2 base "#60C080")
	(gimp-image-select-color img 0 base "#40C090")
	(gimp-image-select-color img 0 base "#20C0C0")
	(gimp-palette-set-foreground "#0a9a76")
	(gimp-edit-fill mixed-forest-layer 0)
	
	(set! coniferous-forest-layer (car (gimp-layer-new img 4096 2048 1 "Coniferous Forest" 100 0)))
	(gimp-image-add-layer img coniferous-forest-layer 0)
	(gimp-image-select-color img 2 base "#60A080")
	(gimp-image-select-color img 0 base "#40A090")
	(gimp-image-select-color img 0 base "#20A0C0")
	(gimp-palette-set-foreground "#1d6060")
	(gimp-edit-fill coniferous-forest-layer 0)
	
	(set! cold-parklands-layer (car (gimp-layer-new img 4096 2048 1 "Cold Parklands" 100 0)))
	(gimp-image-add-layer img cold-parklands-layer 0)
	(gimp-image-select-color img 2 base "#808080")
	(gimp-image-select-color img 0 base "#A0A080")
	(gimp-image-select-color img 0 base "#80A080")
	(gimp-palette-set-foreground "#90907a")
	(gimp-edit-fill cold-parklands-layer 0)
	
	(set! tundra-layer (car (gimp-layer-new img 4096 2048 1 "Tundra" 100 0)))
	(gimp-image-add-layer img tundra-layer 0)
	(gimp-image-select-color img 2 base "#608080")
	(gimp-image-select-color img 0 base "#408080")
	(gimp-image-select-color img 0 base "#2080C0")
	(gimp-palette-set-foreground "#0f3b3b")
	(gimp-edit-fill tundra-layer 0)
	
	(set! ice-layer (car (gimp-layer-new img 4096 2048 1 "Ice" 100 0)))
	(gimp-image-add-layer img ice-layer 0)
	(gimp-image-select-color img 2 base "#FFFFFF")
	(gimp-image-select-color img 0 base "#C0C0C0")
	(gimp-palette-set-foreground "#FFFFFF")
	(gimp-edit-fill ice-layer 0)

))
(script-fu-register
    "script-fu-biomes-and-vegetation"           ;func name
    "Biomes"                                    ;menu label
    "Creates separate layers for each\
	individual biome, groups them by\
	vegetation types, then creates a layer\
	with color coded vegetation types."         ;description
    "Evan Sampson"                              ;author
    "copyright 2014, Evan Sampson"              ;copyright notice
    "October 24, 2014"                          ;date created
    ""                                          ;image type that the script works on
    SF-IMAGE      "Image"        0         
    SF-DRAWABLE   "Base layer"   0	
)
(script-fu-menu-register "script-fu-biomes-and-vegetation" "<Image>/Filters/Biomes")